### ISSUE TITLE
SLAE-Code.zip

### ISSUE THREAD

**Issue by A11riseforme** [SYANiDE-/SLAE-32#1]
is is possible to upload SLAE-Code.zip as well? Thank you!

**Comment by SYANiDE-** [comment]
Not quite sure I understand... I don't recall there being a SLAE-Code.zip.   Do you have a link to this so I can determine what you're looking at?

**Comment by A11riseforme** [comment]
> 
> 
> Not quite sure I understand... I don't recall there being a SLAE-Code.zip. Do you have a link to this so I can determine what you're looking at?

Sorry didn't make myself clear. I referred to the .gitignore file, and found SLAE-Code.zip was excluded from the repo, so I was wondering if you still have this file and mind sharing.

**Comment by SYANiDE-** [comment]
Aaah, I see.  Well I just analyzed the file in question, and I can tell you that it's precisely the same thing as is in the repository.  What happened is I zipped up my entire working directory on my VM which I was studying for and taking this course/certification, and moved it to my host OS.   I then created the repository and unzipped into the repository.  Then pushed. 

There is nothing extra missing from the repository which is also in that zip, save for third-party artifacts which I myself did not author.  Everything here in this repo is of my own making.

You can just as easily download the zip version of the repository via https://github.com/SYANiDE-/SLAE-32/archive/master.zip

Cheers!

**Comment by A11riseforme** [comment]
I see. Thank you so much!
